### ISSUE TITLE
MQTT broker connection isn't reestablished after TCP shutdown

### ISSUE THREAD

**Issue by dnadlinger** [quartiq/smoltcp-nal#24]
If the broker TCP socket gets shut down by the server side, for instance because the broker process is terminated, Stabilizer never reconnects, as smoltcp-nal's "internal socket" (i.e. the smoltcp socket) remains `is_open` (but not `may_send` and `may_recv`):
https://github.com/quartiq/smoltcp-nal/blob/d05120cc9703feb0698e91677c22c413edea6235/src/lib.rs#L120-L123

This is possibly an issue in either smoltcp-nal, minimq or the embedded-nal API design.

**Comment by ryan-summers** [comment]
I have confirmed this is likely still an issue, but is at the smoltcp-nal layer, so I've moved it to the appropriate repository. I'll investigate a fix

**Comment by ryan-summers** [comment]
What I believe is happening:
1. Broker closes it's transmit side
2. Smoltcp maintains the TCP connection, as no one has told it to close the other side
3. Stabilizer / applications can continue sending data over the TCP connection
4. Eventually, when trying to read data from the socket, Stabilizer notices an error reading, but logs it and moves on

At step (4), `minimq` should be detecting the ReadFailure and causing that to disconnect the socket, as that's indicative that the TCP connection is no longer active.

I'm going to see if I can reproduce this behavior locally.

**Comment by ryan-summers** [comment]
Closing. This was found to be a combination of #25 and https://github.com/quartiq/minimq/issues/28
