### ISSUE TITLE
smoltcp 0.9

### ISSUE THREAD

**Issue by jordens** [quartiq/smoltcp-nal#40]
https://github.com/smoltcp-rs/smoltcp/blob/master/CHANGELOG.md#090---2023-02-06

**Comment by ryan-summers** [comment]
I've been taking a look at switching things over - this likely won't have a huge impact on functionality, but it would be cool to get some DNS traits operational as well!

The main changes are around ownership of the smoltcp interface. I'll see if I can get a PR up shortly
